baseURL = "https://haunt98.github.io/blog-hugo/"
languageCode = "en-us"
title = "Yoshie's blog"
theme = "tuyhoa"

# https://gohugo.io/content-management/urls/#canonicalization
canonifyURLs = true

[params]
description = "TODO: My site description"

[[menu.main]]
name = "About"
url = "/"

[[menu.main]]
name = "Posts"
url = "/posts/"

[[menu.main]]
name = "Tags"
url = "/tags/"
