baseURL = "http://example.org/"
languageCode = "en-us"
title = "Yoshie's blog"
theme = "tuyhoa"

[params]
description = "TODO: My site description"

[[menu.main]]
name = "About"
url = "/"

[[menu.main]]
name = "Posts"
url = "/posts/"

[[menu.main]]
name = "Tags"
url = "/tags/"
